name = "rudl-dl-v2"
compatibility_date = "2025-10-03"
main = ".vercel/output/functions/index.js"  # Pages Functions build 輸出
pages_build_output_dir = ".vercel/output/static"

[vars]
# 需要的常數可以一起放這裡

[[d1_databases]]
"binding": "DB",
"database_name": "rudl_app",
"database_id": "6971cadc-b4f7-4642-bc78-f1e5e1bee999"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "dataruapp-files"
